algo = input('Digite algo: ')
print('O tipo primitivo de {} é {}'.format(algo, type(algo)))
print('Só tem espaço? {}'.format(algo.isspace()))
print('É um número? {}'.format(algo.isnumeric()))
print('É alfabético? {}'.format(algo.isalpha()))
print('É alfanumérico? {}'.format(algo.isalnum()))
print('Está em minúsculas? {}'.format(algo.islower()))
print('Está em maiúsculas? {}'.format(algo.isupper()))
print('Está capitalizada? {}'.format(algo.istitle()))