valor = int(input('Digite o valor: '))
print('-'*11)
print('{} x {} = {}'.format(1, valor, valor*1))
print('{} x {} = {}'.format(2, valor, valor*2))
print('{} x {} = {}'.format(3, valor, valor*3))
print('{} x {} = {}'.format(4, valor, valor*4))
print('{} x {} = {}'.format(5, valor, valor*5))
print('{} x {} = {}'.format(6, valor, valor*6))
print('{} x {} = {}'.format(7, valor, valor*7))
print('{} x {} = {}'.format(8, valor, valor*8))
print('{} x {} = {}'.format(9, valor, valor*9))
print('{} x {} = {}'.format(10, valor, valor*10))
print('-'*11)